/* Inventory and stats share the live run state; opening either pauses combat. */
const owned58=new Map();
const cardHistory58=[];
for(const blessing of blessings){const apply=blessing[4];blessing[4]=function(){const result=apply.apply(this,arguments);const item=owned58.get(blessing[1]);owned58.set(blessing[1],{name:blessing[1],rarity:blessing[0],description:blessing[2],count:(item?.count||0)+1});cardHistory58.push({round:w,name:blessing[1],rarity:blessing[0],description:blessing[2]});return result}}
const reset58=reset;reset=function(){owned58.clear();cardHistory58.length=0;return reset58.apply(this,arguments)};
const inventoryStyle58=document.createElement('style');inventoryStyle58.textContent=`
#status{display:none!important}.inventoryDock58{position:fixed;left:24px;bottom:24px;display:flex;gap:9px;z-index:20}.inventoryDock58 button{border:1px solid #9c875255;border-radius:4px;background:linear-gradient(#202a32ee,#0a1119ee);color:#e0d3b6;padding:12px 17px;font:12px Arial;cursor:pointer;box-shadow:0 5px 18px #0006}.inventoryDock58 kbd{margin-left:12px;color:#a49b89;font-size:10px}.inventoryDock58 button:disabled{opacity:.35;cursor:default}
#inventory58{width:min(760px,calc(100vw - 30px));max-height:85vh;overflow:auto;padding:0;color:#e9e0ce;background:linear-gradient(130deg,#1b252e,#0a111a 65%);border:1px solid #b19a665e;border-radius:8px;box-shadow:0 30px 120px #000c;font:14px Arial}#inventory58::backdrop{background:#02060aca;backdrop-filter:blur(6px)}
.inventoryHeader58{display:flex;justify-content:space-between;align-items:center;padding:23px 27px;border-bottom:1px solid #b9a87925}.inventoryHeader58 h2{font:400 25px Georgia;margin:0}.inventoryHeader58 small{display:block;margin-top:8px;color:#9ba6ae;font:10px Arial;letter-spacing:.14em}.inventoryClose58{background:transparent;border:1px solid #a89b7955;border-radius:3px;color:#d9ceb7;padding:8px 11px;cursor:pointer}.inventoryTabs58{display:flex;gap:9px;padding:17px 27px 0}.inventoryTabs58 button{background:transparent;border:0;border-bottom:2px solid transparent;padding:10px 17px;color:#889aa6;cursor:pointer}.inventoryTabs58 button[aria-selected=true]{border-color:#d2b679;color:#ebd6a6}.inventoryBody58{padding:23px 27px 28px}.item58{display:grid;grid-template-columns:46px 1fr auto;gap:15px;align-items:center;background:#070e1680;border:1px solid #ac9b752b;border-radius:4px;padding:16px;margin-bottom:12px}.itemIcon58{width:44px;height:50px;display:grid;place-items:center;color:#e6bc71;background:#ce9e4920;border:1px solid #ce9e4944}.itemIcon58 svg{width:25px;height:36px}.item58 h3{font:400 17px Georgia;margin:0 0 6px}.item58 p{font-size:12px;line-height:1.6;color:#9dadb8;margin:0}.item58 button{background:#d4b77b;color:#111925;border:0;border-radius:3px;padding:10px 14px;font-weight:700;cursor:pointer}.item58 button:disabled{opacity:.4;cursor:default}.inventorySection58{font:11px Arial;letter-spacing:.14em;color:#c8b889;margin:26px 0 12px}.relicGrid58{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.relic58{padding:15px;border:1px solid #778a9844;border-left:2px solid #9eaeb9;border-radius:3px;background:#080f1788}.relic58[data-grade=rare]{border-left-color:#81bad7}.relic58[data-grade=epic]{border-left-color:#bf9bdd}.relic58[data-grade=legendary]{border-left-color:#eac06b}.relic58 strong{font:15px Georgia;display:block;margin:6px 0}.relic58 small{color:#a5b4c0;font-size:10px}.relic58 p{color:#a9b5be;font-size:12px;line-height:1.6;margin-bottom:0}.statsGrid58{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:#bda56d24;border:1px solid #bda56d24}.stat58{display:flex;justify-content:space-between;gap:12px;padding:16px;background:#0c151f}.stat58 span{color:#9faeb9;font-size:12px}.stat58 strong{color:#eee1be;font:15px Georgia;font-variant-numeric:tabular-nums}.inventoryEmpty58{color:#81939f;line-height:1.8;padding:18px;border:1px dashed #92a0a533}.inventoryNote58{font-size:11px;line-height:1.7;color:#8d9daa;margin-top:15px}
@media(max-width:600px){.inventoryDock58{left:12px;bottom:14px}.inventoryDock58 button{padding:10px}.inventoryHeader58,.inventoryBody58{padding:18px}.inventoryTabs58{padding-left:18px}.relicGrid58,.statsGrid58{grid-template-columns:1fr}.item58{grid-template-columns:35px 1fr;gap:12px}.item58 button{grid-column:2}.itemIcon58{width:35px}}
`;document.head.appendChild(inventoryStyle58);
const dock58=document.createElement('div');dock58.className='inventoryDock58';dock58.innerHTML='<button type="button" data-tab="bag">가방 <kbd>B</kbd></button><button type="button" data-tab="stats">능력치 <kbd>C</kbd></button>';document.body.appendChild(dock58);
const dialog58=document.createElement('dialog');dialog58.id='inventory58';dialog58.setAttribute('aria-labelledby','inventoryTitle58');dialog58.innerHTML='<header class="inventoryHeader58"><div><h2 id="inventoryTitle58">여행자의 가방</h2><small>전투 일시정지</small></div><button class="inventoryClose58" type="button" aria-label="닫기">닫기 · ESC</button></header><div class="inventoryTabs58" role="tablist"><button type="button" data-tab="bag" role="tab">가방</button><button type="button" data-tab="stats" role="tab">능력치</button></div><div class="inventoryBody58" role="tabpanel"></div>';document.body.appendChild(dialog58);
const escape58=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let resume58=false,tab58='bag',returnFocus58=null;
function stats58(){const f=V8_FORMS[weapon];return [['직업',K[weapon][0]],['레벨',lv],['현재 라운드',w+' / 100'],['경험치',xp+' / '+need],['체력',Math.ceil(p.hp)+' / '+P.h],['스태미나',Math.ceil(p.st)+' / '+P.s],['공격력 배율','× '+P.d.toFixed(2)],['공격 속도','× '+attackSpeed.toFixed(2)],['피해 감소',Math.round(P.arm*100)+'%'],['치명타 확률',Math.round(P.crit*100)+'%'],['흡혈',Math.round(P.leech*100)+'%'],['이동 속도','× '+P.spd.toFixed(2)],['기본 / 강공격 사거리',f.range.join(' / ')],['포션 회복량',potionPower+' HP'],['연쇄 공격 확률',Math.round(chainChance*100)+'%'],['부활',phoenixOwned?(phoenix?'이번 라운드 사용 가능':'이번 라운드 소진'):'미보유']]}
function renderInventory58(){
 dialog58.querySelector('h2').textContent=tab58==='bag'?'여행자의 가방':'캐릭터 능력치';
 dialog58.querySelectorAll('[role=tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab58)));
 const body=dialog58.querySelector('.inventoryBody58');
 if(tab58==='stats'){body.innerHTML='<div class="statsGrid58">'+stats58().map(([n,v])=>'<div class="stat58"><span>'+escape58(n)+'</span><strong>'+escape58(v)+'</strong></div>').join('')+'</div><p class="inventoryNote58">현재 캐릭터와 획득한 카드의 효과가 반영된 수치입니다.</p><h3 class="inventorySection58">선택한 카드 기록 · '+cardHistory58.length+'</h3>'+(cardHistory58.length?'<div class="relicGrid58">'+cardHistory58.map((x,i)=>'<article class="relic58" data-grade="'+x.rarity+'"><small>#'+(i+1)+' · ROUND '+x.round+' · '+escape58(rarity[x.rarity].name)+'</small><strong>'+escape58(x.name)+'</strong><p>'+escape58(x.description)+'</p></article>').join('')+'</div>':'<div class="inventoryEmpty58">아직 선택한 카드가 없습니다.</div>');return}
 const usable=p.flask>0&&p.hp<P.h&&!p.attack&&!p.roll&&!p.hurt&&drinkT12<=0;
 body.innerHTML='<div class="item58"><div class="itemIcon58"><svg viewBox="0 0 32 44" fill="none" aria-hidden="true"><path d="M11 3h10v6l-2 3v5c8 4 11 15 6 22H7c-5-7-2-18 6-22v-5l-2-3V3Z" stroke="currentColor" stroke-width="1.5"/><path d="M8 29h16l-1 8H9l-1-8Z" fill="currentColor" opacity=".7"/><path d="M10 8h12" stroke="currentColor"/></svg></div><div><h3>불씨 플라스크 × '+p.flask+'</h3><p>체력을 최대 '+potionPower+' 회복합니다.<br>전투 중 F 키로도 사용할 수 있습니다.</p></div><button type="button" id="useFlask58" '+(usable?'':'disabled')+'>마시기</button></div><div class="item58"><div class="itemIcon58">◆</div><div><h3>보유 룬</h3><p>이번 원정에서 획득한 룬</p></div><strong>'+runes+'</strong></div><h3 class="inventorySection58">획득한 성장 카드 · '+[...owned58.values()].reduce((n,x)=>n+x.count,0)+'</h3>'+(owned58.size?'<div class="relicGrid58">'+[...owned58.values()].map(x=>'<article class="relic58" data-grade="'+x.rarity+'"><small>'+escape58(rarity[x.rarity].name)+' · ×'+x.count+'</small><strong>'+escape58(x.name)+'</strong><p>'+escape58(x.description)+'</p></article>').join('')+'</div>':'<div class="inventoryEmpty58">아직 획득한 카드가 없습니다.<br>라운드를 완료하고 선택한 카드가 여기에 기록됩니다.</div>')+'<p class="inventoryNote58">가방은 이번 원정 동안 유지되며, 새 게임을 시작하면 초기화됩니다.</p>';
 body.querySelector('#useFlask58').onclick=()=>{closeInventory58();heal()};
}
function closeInventory58(){if(!dialog58.open)return;dialog58.close();if(resume58)run=1;resume58=false;returnFocus58?.focus();}
function openInventory58(tab){if(!dialog58.open){if(!run)return;resume58=!!run;run=0;for(const k of Object.keys(keys))keys[k]=0;returnFocus58=document.activeElement;dialog58.showModal()}tab58=tab;renderInventory58();dialog58.querySelector('.inventoryClose58').focus()}
for(const element of [dock58,dialog58]){element.addEventListener('mousedown',e=>e.stopPropagation());element.addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)openInventory58(b.dataset.tab)})}
dialog58.querySelector('.inventoryClose58').onclick=closeInventory58;dialog58.addEventListener('cancel',e=>{e.preventDefault();closeInventory58()});
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(dialog58.open){e.stopImmediatePropagation();if(k==='escape'){e.preventDefault();closeInventory58()}else if(!e.repeat&&(k==='b'||k==='c')){e.preventDefault();openInventory58(k==='b'?'bag':'stats')}return}if(!e.repeat&&!e.ctrlKey&&!e.altKey&&!e.metaKey&&(k==='b'||k==='c')){e.preventDefault();e.stopImmediatePropagation();openInventory58(k==='b'?'bag':'stats')}},true);
const ui58=ui;ui=function(){ui58();dock58.querySelectorAll('button').forEach(b=>b.disabled=!run&&!dialog58.open)};
