const V19=document.createElement('style');V19.textContent='.extreme19{position:fixed;right:22px;top:116px;z-index:16;padding:6px 10px;border:1px solid #ff405d88;background:#12050bd9;color:#ff647b;font:800 10px Arial;letter-spacing:.18em}.card .v19boost{display:block;margin-top:9px;color:#ffcf72;font:800 10px Arial}';document.head.appendChild(V19);document.body.insertAdjacentHTML('beforeend','<div class=extreme19>EXTREME COVENANT · v19</div>');
function cell19(s,cols,rows,col,row,x,y,dh,face=1,alpha=1,rot=0){if(!s||!s.width)return false;let cw=s.width/cols,ch=s.height/rows,edge=rows===4?.15:.09,ix=Math.max(7,cw*edge|0),iy=Math.max(3,ch*.018|0),sw=cw-ix*2,sh=ch-iy*2,dw=sw/sh*dh;X.save();X.translate(x,y);X.scale(face,1);X.rotate(rot*face);X.globalAlpha=alpha;X.imageSmoothingEnabled=true;X.imageSmoothingQuality='high';X.beginPath();X.rect(-dw/2,-dh,dw,dh);X.clip();X.drawImage(s,col*cw+ix,row*ch+iy,sw,sh,-dw/2,-dh,dw,dh);X.restore();return true}
const R18=spriteActor;spriteActor=function(e,pl=0){if(!pl)return R18(e,0);let s=weapon===1?LC15:CLEAN10;if(!s||!s.width)return R18(e,1);let z=p.attackMax?1-p.attack/p.attackMax:0,fr=p.parry?6:p.hurt?7:p.attack?(z<.27?3:z<.63?4:5):p.roll?2:p.move?1+(Math.floor(p.step*.72)&1):0,a=p.attack?(p.swingAng??p.ang):p.ang,f=Math.cos(a)<0?-1:1,dh=[190,218,210,198][weapon],bob=p.move?Math.sin(p.step*.7)*1.8:0,l=p.attack?Math.sin(Math.min(1,z/.7)*Math.PI)*(p.heavy?46:32):0,rot=p.roll?.1:(p.attack?(z-.48)*[.11,.035,.16,.06][weapon]:0),al=p.hurt?.7:p.roll?.76:1;return cell19(s,8,weapon===1?1:4,fr,weapon===1?0:weapon,p.x+Math.cos(a)*l,p.y+9-bob+Math.sin(a)*l*.28,dh,f,al,rot)};
const B19={common:[1.12,18,14,.025],rare:[1.18,28,20,.04],epic:[1.28,42,28,.065],legendary:[1.42,65,40,.1]};blessings.forEach(b=>{let fn=b[4],q=B19[b[0]];b[2]+=' · OVERCHARGED';b[3]+=' / +POWER';b[4]=()=>{fn();P.d*=q[0];P.h+=q[1];p.hp=Math.min(P.h,p.hp+q[1]);P.s+=q[2];p.st=P.s;P.crit=Math.min(.82,P.crit+q[3])}});
const O19=offer;offer=function(){O19();document.querySelectorAll('#cards .card').forEach(c=>{let s=document.createElement('span');s.className='v19boost';s.textContent='OVERCHARGED COVENANT';c.appendChild(s)})};
const RD19=startRound;startRound=function(){let old=p?.hp||0;RD19();let n=Math.min(9,3+Math.floor((w-1)/12)),t=enemies.find(e=>!e.boss)||enemies[0];for(let i=0;t&&!t.boss&&i<n;i++){let a=i*Math.PI*2/n,e=spawn(clamp(W*(.72+Math.cos(a)*.19),45,W-45),clamp(H*(.68+Math.sin(a)*.18),H*.49,H-40),0);e.kind=(i+w)%4;e.elite=w>8&&(i+w)%3===0;e.hp=e.max=t.max;e.reward=t.reward||25}let hm=2.15+(w-1)*.018;enemies.forEach((e,i)=>{e.hp=e.max=Math.round(e.max*hm*(e.boss?1.28:1));e.attackMax=Math.max(.24,e.attackMax*(.62-Math.min(.18,w*.0018)));e.s14=(e.s14||1)*(1.28+Math.min(.48,w*.0048));if(w>15&&(i+w)%3===0)e.elite=true});if(old>0)p.hp=Math.min(p.hp,old+P.h*.1);message('EXTREME NIGHT '+w+' · TIER '+(1+Math.floor((w-1)/10)),1300)};
const PH19=playerHurt;playerHurt=function(n,e){PH19(Math.ceil(n*(1.75+Math.min(1.05,(w-1)*.011))),e)};
let hit19=[],spark19=[];const ST19=strike;strike=function(e,n){let hp=e?.hp||0;ST19(e,n);if(e&&e.hp<hp){let c=V8_FORMS[weapon].color,a=p.swingAng??p.ang;hit19.push({x:e.x,y:e.y-48,r:8,life:.34,c});for(let i=0;i<7;i++){let q=a-.72*Math.PI+Math.random()*1.44*Math.PI,s=130+Math.random()*340;spark19.push({x:e.x,y:e.y-48,vx:Math.cos(q)*s,vy:Math.sin(q)*s,life:.16+Math.random()*.22,c:i%3?'#fff':c})}if(hit19.length>14)hit19.splice(0,hit19.length-14);if(spark19.length>84)spark19.splice(0,spark19.length-84);shake=Math.max(shake,p.heavy?20:12)}};
const U19=update;update=function(dt){U19(dt);hit19.forEach(q=>{q.life-=dt;q.r+=dt*260});hit19=hit19.filter(q=>q.life>0);spark19.forEach(q=>{q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.94;q.vy*=.94});spark19=spark19.filter(q=>q.life>0)};
const D19=draw;draw=function(){D19();X.save();X.globalCompositeOperation='screen';hit19.forEach(q=>{X.globalAlpha=q.life/.34;X.strokeStyle=q.c;X.shadowBlur=26;X.shadowColor=q.c;X.lineWidth=2+q.life*18;X.beginPath();X.arc(q.x,q.y,q.r,0,7);X.stroke()});spark19.forEach(q=>{X.globalAlpha=Math.min(1,q.life/.14);X.strokeStyle=q.c;X.shadowBlur=9;X.shadowColor=q.c;X.lineWidth=1.5;X.beginPath();X.moveTo(q.x,q.y);X.lineTo(q.x-q.vx*.045,q.y-q.vy*.045);X.stroke()});X.restore()};
const RS19=reset;reset=function(){hit19=[];spark19=[];RS19()};
const SOLO21=['ash-knight-solo.png','moon-lancer-solo.png'].map(src=>{let i=new Image();i.src=src;return i});
const SPRITE20=spriteActor;spriteActor=function(e,pl=0){if(!pl||weapon>1)return SPRITE20(e,pl);let img=SOLO21[weapon];if(!img.complete||!img.naturalWidth)return SPRITE20(e,pl);let a=p.attack?(p.swingAng??p.ang):p.ang,face=Math.cos(a)<0?-1:1,z=p.attackMax?1-p.attack/p.attackMax:0,attack=p.attack&&p.attackMax,bob=p.move?Math.sin(p.step*.72)*3:Math.sin(time*2)*.7,lunge=attack?Math.sin(z*Math.PI)*(weapon===1?(p.heavy?58:43):(p.heavy?29:20)):0,swing=attack?(weapon===1?(z<.32?-.1:(z-.32)*.15):(z<.32?-.2:(z-.32)*.55)):p.move?Math.sin(p.step*.36)*.018:0,dh=weapon===1?232:218,dw=img.naturalWidth/img.naturalHeight*dh;X.save();X.translate(p.x+Math.cos(a)*lunge,p.y+10-bob+Math.sin(a)*lunge*.28);X.scale(face,1);X.rotate(swing*face);if(p.roll){X.rotate(face*.18);X.globalAlpha=.72}if(p.hurt)X.globalAlpha=.68;X.imageSmoothingEnabled=true;X.imageSmoothingQuality='high';X.drawImage(img,-dw/2,-dh,dw,dh);X.restore();return true};
const ROUND20=startRound;startRound=function(){ROUND20();let oldHm=2.15+(w-1)*.018,newHm=1.35+(w-1)*.008,oldAtk=.62-Math.min(.18,w*.0018),newAtk=.82-Math.min(.08,w*.0008),oldSp=1.28+Math.min(.48,w*.0048),newSp=1.10+Math.min(.20,w*.002);enemies.forEach(e=>{e.hp=e.max=Math.max(1,Math.round(e.max/oldHm*newHm));e.attackMax=Math.max(.32,e.attackMax/oldAtk*newAtk);e.s14=(e.s14||1)/oldSp*newSp});if(!enemies.some(e=>e.boss)){let keep=R[w-1][1]+Math.min(4,1+Math.floor((w-1)/25));if(enemies.length>keep)enemies.splice(keep)}message('NIGHT '+w+' · HARD',900)};
const DAMAGE20=playerHurt;playerHurt=function(n,e){let old=1.75+Math.min(1.05,(w-1)*.011),fair=1.18+Math.min(.34,(w-1)*.004);DAMAGE20(n*fair/old,e)};
const BODY21=[],RAW21=['body-sword.png','body-lancer.png','body-axe.png','body-mage.png'].map((src,i)=>{let im=new Image();im.src=src;im.onload=()=>blackKey12(im,c=>BODY21[i]=c);return im});
function weapon21(x,y,a,z,att,heavy,face){let c=V8_FORMS[weapon].color,handX=x+face*13,handY=y-105,phase=att?clamp(z,0,1):0,rot;if(weapon===1)rot=a;else rot=att?(phase<.28?a-2.15+(phase/.28)*.42:a-1.73+((phase-.28)/.72)*2.95):a-.72;if(weapon===3)rot=att?a-1.25+Math.sin(phase*Math.PI)*1.05:a-.9;let reach=weapon===0?(heavy?112:92):weapon===1?(heavy?178:148):weapon===2?(heavy?125:105):92,thrust=weapon===1&&att?Math.sin(Math.min(1,phase/.62)*Math.PI)*(heavy?72:54):0,sx=handX+Math.cos(a)*thrust,sy=handY+Math.sin(a)*thrust*.35,ex=sx+Math.cos(rot)*reach,ey=sy+Math.sin(rot)*reach;X.save();X.globalCompositeOperation='screen';X.shadowBlur=att?18:8;X.shadowColor=c;X.strokeStyle=weapon===2?'#6b3b2c':weapon===3?'#593177':'#9aa9b4';X.lineWidth=weapon===1?6:weapon===2?10:7;X.lineCap='round';X.beginPath();X.moveTo(sx,sy);X.lineTo(ex,ey);X.stroke();X.fillStyle=c;if(weapon===0){X.beginPath();X.moveTo(ex,ey);X.lineTo(ex-Math.cos(rot-.18)*18,ey-Math.sin(rot-.18)*18);X.lineTo(ex-Math.cos(rot+.18)*18,ey-Math.sin(rot+.18)*18);X.fill()}else if(weapon===1){X.beginPath();X.moveTo(ex+Math.cos(rot)*20,ey+Math.sin(rot)*20);X.lineTo(ex+Math.cos(rot+2.55)*15,ey+Math.sin(rot+2.55)*15);X.lineTo(ex+Math.cos(rot-2.55)*15,ey+Math.sin(rot-2.55)*15);X.fill()}else if(weapon===2){X.save();X.translate(ex,ey);X.rotate(rot);X.fillRect(-8,-24,34,48);X.restore()}else{let rr=att?12+Math.sin(phase*Math.PI)*22:11;X.beginPath();X.arc(ex,ey,rr,0,7);X.fill();X.strokeStyle='#fff';X.lineWidth=2;X.beginPath();X.arc(ex,ey,rr+8,time,time+4.7);X.stroke()}if(att&&weapon!==1){X.globalAlpha=Math.sin(phase*Math.PI)*.65;X.strokeStyle=c;X.lineWidth=heavy?16:9;X.beginPath();X.arc(handX,handY,reach,rot-.55,rot+.55);X.stroke()}X.restore()}
const SPRITE21=spriteActor;spriteActor=function(e,pl=0){if(!pl)return SPRITE21(e,0);let img=BODY21[weapon];if(!img)return SPRITE21(e,1);let a=p.attack?(p.swingAng??p.ang):p.ang,face=Math.cos(a)<0?-1:1,z=p.attackMax?1-p.attack/p.attackMax:0,att=!!(p.attack&&p.attackMax),bob=p.move?Math.sin(p.step*.72)*3:0,recoil=att?Math.sin(z*Math.PI)*(weapon===2?.11:weapon===3?-.07:.055):0,lunge=att?Math.sin(z*Math.PI)*[18,38,14,8][weapon]:0,dh=[205,208,218,212][weapon],dw=img.width/img.height*dh;X.save();X.translate(p.x+Math.cos(a)*lunge,p.y+9-bob+Math.sin(a)*lunge*.25);X.scale(face,1);X.rotate(recoil*face);if(p.roll){X.rotate(face*.22);X.globalAlpha=.72}if(p.hurt)X.globalAlpha=.66;X.imageSmoothingEnabled=true;X.drawImage(img,-dw/2,-dh,dw,dh);X.restore();weapon21(p.x+Math.cos(a)*lunge,p.y+9-bob,a,z,att,p.heavy,face);return true};
